#index:
#    path: /
#    controller: Maximus\Controller\DefaultController::index

custom_page:
    path: /{viewName}
    controller: Maximus\Controller\CustomPageController::pageAction

article:
    path: /{year}/{month}/{day}/{alias}.{format}
    controller: Maximus\Controller\ArticleController::article
    defaults:
        format: ''
    requirements:
        year: '\d{4}'
        month: '\d{2}'
        day: '\d{2}'
        format: 'html|md'
