#index:
#    path: /
#    controller: Maximus\Controller\DefaultController::index

custom_page:
    path: /{viewName}
    controller: Maximus\Controller\CustomPageController::pageAction

article:
    path: /{year}/{month}/{day}/{title}
    controller: Maximus\Controller\ArticleController::indexAction
    requirements:
        year: '\d{4}'
        month: '\d{2}'
        day: '\d{2}'
